apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sim4d

resources:
- namespace.yaml
- studio-deployment.yaml
- studio-service.yaml
- network-policies.yaml

images:
- digest: sha256:d745b2263802e7e4fe25834c3e2cdf7c3d1708d7c0d8d669e5f94ffb8b6e077b
  name: ghcr.io/madfam-org/sim4d-studio
  newName: ghcr.io/madfam-org/sim4d-studio
