apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sim4d

resources:
- namespace.yaml
- studio-deployment.yaml
- studio-service.yaml
- network-policies.yaml

images:
- digest: sha256:749e1a6b9ac6e150eb17b9127dd9d48c5cdd3b5cbdb35c9b9c7042c9755e2fc8
  name: ghcr.io/madfam-org/sim4d-studio
  newName: ghcr.io/madfam-org/sim4d-studio
