apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sim4d

resources:
- namespace.yaml
- studio-deployment.yaml
- studio-service.yaml
- network-policies.yaml

images:
- digest: sha256:b5981a39ca1cb26dff321249f6673aa57357eb81ab59ac6cf3b9364031947974
  name: ghcr.io/madfam-org/sim4d-studio
  newName: ghcr.io/madfam-org/sim4d-studio
