apiVersion: v1
kind: Service
metadata:
  name: sim4d-studio
  namespace: sim4d
spec:
  selector:
    app: sim4d-studio
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
  type: ClusterIP
